version: "3.8"

services:
  api:
    image: auxiliarist-be #change this
    build:
      context: .
      target: dev
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - "5050:5050"
    environment:
      - REDIS_URL=redis://cache
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0.36
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: auxiliaristDB #change this
      MYSQL_USER: user
      MYSQL_PASSWORD: example
    ports:
      - "33061:3306"
    volumes:
      - ./docker/data/db:/var/lib/mysql

  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
